#region License Information (GPL v3)

/*
    ShareX - A program that allows you to take screenshots and share any file type
    Copyright © 2007-2015 ShareX Developers

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

    Optionally you can also view the license at <http://www.gnu.org/licenses/>.
*/

#endregion License Information (GPL v3)

using ShareX.HelpersLib;
using System;
using System.IO;
using System.Text;
using System.Windows.Forms;

namespace ShareX.IndexerLib
{
    public abstract class Indexer
    {
        private const string INDEXER_FOOTER_FORMAT = "Generated by ShareX {0} on {1}. Latest version can be downloaded from: {2}";
        protected const string DATE_FORMAT = "yyyy-MM-dd 'at' HH:mm:ss 'UTC'";

        private const string FILE_DESCRIPTION_ROW_FORMAT = "{0}{1} [{2}]";
        private const string FOLDER_DESCRIPTION_ROW_FORMAT = "{0}{1}";
        private const string FOLDER_DESCRIPTION_ROW_SIZE_FORMAT = " [{0}]";

        protected IndexerSettings config = null;
        protected StringBuilder sbContent = new StringBuilder();

        public DirectoryFileInfo DirectoryFileInfo { get; private set; }

        public static Indexer IndexerImpl { get; private set; }
        protected Indexer(IndexerSettings indexerSettings)
        {
            config = indexerSettings;
        }

        public static string Index(string folderPath, IndexerSettings config)
        {
            IndexerImpl = null;

            switch (config.Output)
            {
                case IndexerOutput.Html:
                    IndexerImpl = new IndexerHtml(config);
                    break;
                case IndexerOutput.Txt:
                    IndexerImpl = new IndexerText(config);
                    break;
                case IndexerOutput.Xml:
                    IndexerImpl = new IndexerXml(config);
                    break;
            }

            return IndexerImpl.Index(folderPath);
        }

        public virtual string Index(string folderPath)
        {
            DirectoryFileInfo = GetFolderInfo(folderPath);
            DirectoryFileInfo.CollectInfo();

            IndexFolder(DirectoryFileInfo);

            return sbContent.ToString();
        }

        /// <summary>
        /// Walk recursively through the directory and collect information about the directory and their files.
        /// </summary>
        /// <param name="folderPath"></param>
        /// <param name="level"></param>
        /// <returns></returns>
        protected DirectoryFileInfo GetFolderInfo(string folderPath, int level = 0)
        {
            DirectoryFileInfo directory_file_info = new DirectoryFileInfo(folderPath);

            if (config.MaxDepthLevel == 0 || level < config.MaxDepthLevel)
            {
                DirectoryInfo currentDirectoryInfo = new DirectoryInfo(folderPath);

                foreach (DirectoryInfo directoryInfo in currentDirectoryInfo.GetDirectories())
                {
                    if (SkipHiddenFolders(directoryInfo))
                        continue;
                    
                    // walk recursivly through all subdirectories and collect their directory and file info
                    DirectoryFileInfo sub_directory = GetFolderInfo(directoryInfo.FullName, level + 1);
                    directory_file_info.Folders.Add(sub_directory);
                    sub_directory.Parent = directory_file_info;
                }

                GetFileInfo(currentDirectoryInfo, directory_file_info);
                directory_file_info.Files.Sort((x, y) => String.CompareOrdinal(x.Name, y.Name));
            }

            return directory_file_info;
        }

        /// <summary>
        /// Collects FileInfos from a directory.
        /// </summary>
        /// <param name="currentDirectoryInfo"></param>
        /// <param name="directory_file_info"></param>
        private void GetFileInfo(DirectoryInfo currentDirectoryInfo, DirectoryFileInfo directory_file_info)
        {
            foreach (FileInfo fileInfo in currentDirectoryInfo.GetFiles())
            {
                if (SkipHiddenFiles(fileInfo))
                    continue;

                directory_file_info.Files.Add(fileInfo);
            }
        }

        private bool SkipHiddenFiles(FileInfo fileInfo)
        {
            return config.SkipHiddenFiles && fileInfo.Attributes.HasFlag(FileAttributes.Hidden);
        }

        private bool SkipHiddenFolders(DirectoryInfo directoryInfo)
        {
            return config.SkipHiddenFolders && directoryInfo.Attributes.HasFlag(FileAttributes.Hidden);
        }

        protected abstract void IndexFolder(DirectoryFileInfo dir, int level = 0);

        protected virtual string GetFolderNameRow(DirectoryFileInfo directory_info, int level = 0)
        {
            string folder_description_text = string.Format(FOLDER_DESCRIPTION_ROW_FORMAT, config.IndentationText.Repeat(level), directory_info.FolderName);

            if (directory_info.DataSize > 0)
                folder_description_text += string.Format(FOLDER_DESCRIPTION_ROW_SIZE_FORMAT, directory_info.DataSize.ToSizeString(config.BinaryUnits));

            return folder_description_text;
        }

        protected virtual string GetFileNameRow(FileInfo fi, int level = 0)
        {
            return string.Format(FILE_DESCRIPTION_ROW_FORMAT, config.IndentationText.Repeat(level), fi.Name, fi.Length.ToSizeString(config.BinaryUnits));
        }

        protected virtual string GetFooter()
        {
            return string.Format(INDEXER_FOOTER_FORMAT, Application.ProductVersion, DateTime.UtcNow.ToString(DATE_FORMAT), Links.URL_WEBSITE);
        }
    }
}